name: helics-environment
channels:
  - conda-forge
  - gmlc-tdc
dependencies:
  - python=3.9
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pip
  - pip:
      - OpenDSSDirect.py
      - PYPOWER
      - helics
